### ISSUE TITLE
I am not sure that when you can see this comment, but I am very eager to see your face.

### ISSUE THREAD

**Issue by Always1739** [elitesuper/Ecommerce-Django-NextJS#4]
I am not sure that when you can see this comment, but I am very eager to see your face.
Let's book a call and then let me know. My mail is thomas.dev1739@gmail.com

_Originally posted by @Always1739 in https://github.com/elitesuper/Ecommerce-Django-NextJS/discussions/1#discussioncomment-10182960_

**Comment by elitesuper** [comment]
Hello, Long time no see. I've sent email. (wolfgangbaier7712@outlook.com)
